exsitu_tcn_common_search_json:
    path:  /data.js
    defaults: { _controller: ExsituTcnCommonBundle:Search:allProducts }
    schemes:  [https|http]

exsitu_tcn_common_category:
    path:  /{slug}/
    defaults: { _controller: ExsituTcnCommonBundle:Category:index }
    schemes:  [https|http]

exsitu_tcn_common_review:
    path:  /{categorySlug}/{reviewSlug}
    defaults: { _controller: ExsituTcnCommonBundle:Review:index }
    schemes:  [https|http]

exsitu_tcn_common_home:
    path:  /
    defaults: { _controller: ExsituTcnCommonBundle:Home:index }
    schemes:  [https|http]
