services:
#    tcn_common.example:
#        class: Exsitu\TcnCommonBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    memcached:
        class: '\Memcached'

    tcn.data.service:
        class: Exsitu\TcnCommonBundle\Service\TcnDataService
        arguments:
          - "@memcached"
          - "%tcn.data.dir%"
          - "%tcn.data.namespace%"
          - "%tcn.data.cacheKey%"

#    tcn.access_control.service:
#            class: Exsitu\TcnCommonBundle\Service\AccessControleService
#            arguments:
#              - "@tcn.data.service"